<?php
namespace GG_Woo_Feed\Common;

class Feed_Template {
	/**
	 * Get feed templates.
	 *
	 * @return array
	 */
	public static function get_feed_templates() {
		$templates = [
			'default'                => [
				'mattributes'   => [
					'id',
					'title',
					'description',
					'link',
					'image_link',
					'price',
					'categories',
					'brand',
				],
				'prefix'        => [ '', '', '', '', '', '', '', '' ],
				'type'          => [
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
				],
				'attributes'    => [ 'id', 'title', 'description', 'link', 'image', 'price', 'product_type', '' ],
				'default'       => [ '', '', '', '', '', '', '', '' ],
				'default_value' => [ '', '', '', '', '', '', '', '' ],
				'suffix'        => [ '', '', '', '', '', '', '', '' ],
				'output_type'   => [ '1', '1', '1', '1', '1', '1', '1', '1' ],
				'limit'         => [ '', '', '', '', '', '', '', '' ],
			],
			'adwords'                => [
				'mattributes'   => [
					'ID',
					'ID2',
					'Item title',
					'Final URL',
					'Image URL',
					'Item subtitle',
					'Item description',
					'Item category',
					'Price',
					'Sale price',
					'Contextual keywords',
					'Item address',
				],
				'prefix'        => [ '', '', '', '', '', '', '', '', '', '', '', '' ],
				'type'          => [
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'pattern',
					'pattern',
				],
				'attributes'    => [
					'id',
					'sku',
					'title',
					'link',
					'image',
					'short_description',
					'description',
					'product_type',
					'price',
					'sale_price',
					'',
					'',
				],
				'default'       => [ '', '', '', '', '', '', '', '', '', '', '', '' ],
				'default_value' => [ '', '', '', '', '', '', '', '', '', '', '', '' ],
				'suffix'        => [ '', '', '', '', '', '', '', '', '', '', '', '' ],
				'output_type'   => [ '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1' ],
				'limit'         => [ '', '', '', '', '', '', '', '', '', '', '', '' ],
			],
			'google_local_inventory' => [
				'mattributes'   => [
					'store code',
					'itemid',
					'quantity',
					'price',
					'sale price',
					'availability',
					'sale price effective date',
					'pickup method',
					'pickup sla',
				],
				'prefix'        => [ '', '', '', '', '', '', '', '', '' ],
				'type'          => [
					'pattern',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'pattern',
					'pattern',
				],
				'attributes'    => [
					'',
					'id',
					'quantity',
					'price',
					'sale_price',
					'availability',
					'sale_price_effective_date',
					'',
					'',
				],
				'default'       => [ ' ', '', '', '', '', '', '', '', '' ],
				'default_value' => [ ' ', '', '', '', '', '', '', '', '' ],
				'suffix'        => [ '', '', '', '', '', '', '', '', '' ],
				'output_type'   => [ '1', '1', '1', '1', '1', '1', '1', '1', '1' ],
				'limit'         => [ '', '', '', '', '', '', '', '', '' ],
			],
			'google_local'           => [
				'mattributes'   => [
					'store code',
					'itemid',
					'title',
					'description',
					'image_link',
					'condition',
					'gtin',
					'brand',
					'google_product_category',
					'webitemid',
					'mpn',
					'price',
					'sale price',
					'sale price effective date',
					'unit_pricing_measure',
					'unit_pricing_base_measure',
					'pickup method',
					'pickup SLA',
					'pickup_link_template',
					'mobile_pickup_link_template',
					'link_template',
					'mobile_link_template',
					'ads_redirect',
					'energy_efficiency_class',
					'energy_efficiency_class_min',
					'energy_efficiency_class_max',
				],
				'prefix'        => [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
				'type'          => [
					'pattern',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'attribute',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'attribute',
					'attribute',
					'attribute',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
					'pattern',
				],
				'attributes'    => [
					'',
					'id',
					'title',
					'description',
					'image',
					'condition',
					'sku',
					'',
					'',
					'',
					'',
					'price',
					'sale_price',
					'sale_price_effective_date',
					'',
					'',
					'',
					'',
					'',
					'',
					'',
					'',
					'',
					'',
					'',
					'',
				],
				'default'       => [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
				'default_value' => [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
				'suffix'        => [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
				'output_type'   => [ '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', ],
				'limit'         => [ '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
			],
		];

		return apply_filters( 'gg_woo_feed_feed_templates', $templates );
	}
}
