<?php
namespace GG_Woo_Feed\Common;

class Provider_Attributes {
	/**
	 * Get Providers.
	 *
	 * @return array
	 */
	public static function get_providers() {
		return [
			'google'    => __( 'Google Shopping', 'gg-woo-feed' ),
			'adwords'   => __( 'Google Adwords', 'gg-woo-feed' ),
			'facebook'  => __( 'Facebook', 'gg-woo-feed' ),
			'pinterest' => __( 'Pinterest', 'gg-woo-feed' ),
		];
	}

	/**
	 * Get Google Attributes.
	 *
	 * @return array
	 */
	public static function get_google_attributes() {
		$attributes = [
			'--1'                        => 'Basic Information',
			'id'                         => 'Product Id[id]',
			'title'                      => 'Product Title[title]',
			'description'                => 'Product Description[description]',
			'link'                       => 'Product URL[link]',
			'mobile_link'                => 'Product URL[mobile_link]',
			'product_type'               => 'Product Categories[product_type] ',
			'google_taxonomy'            => 'Google Product Category[google_product_category]',
			'image'                      => 'Main Image[image_link]',
			'images'                     => 'Additional Images [additional_image_link]',
			'images_1'                   => 'Additional Image 1 [additional_image_link]',
			'images_2'                   => 'Additional Image 2 [additional_image_link]',
			'images_3'                   => 'Additional Image 3 [additional_image_link]',
			'images_4'                   => 'Additional Image 4 [additional_image_link]',
			'images_5'                   => 'Additional Image 5 [additional_image_link]',
			'images_6'                   => 'Additional Image 6 [additional_image_link]',
			'images_7'                   => 'Additional Image 7 [additional_image_link]',
			'images_8'                   => 'Additional Image 8 [additional_image_link]',
			'images_9'                   => 'Additional Image 9 [additional_image_link]',
			'images_10'                  => 'Additional Image 10 [additional_image_link]',
			'condition'                  => 'Condition[condition]',
			'---1'                       => '',
			'--2'                        => 'Availability & Price',
			'availability'               => 'Stock Status[availability]',
			'availability_date'          => 'Availability Date[availability_date]',
			'inventory'                  => 'Facebook Inventory[inventory]',
			'override'                   => 'Facebook Override[override]',
			'price'                      => 'Regular Price[price]',
			'sale_price'                 => 'Sale Price[sale_price]',
			'cost_of_goods_sold'         => 'Cost of Goods Sold[cost_of_goods_sold]',
			'sale_price_effective_date'  => 'Sale Price Effective Date[sale_price_effective_date]',
			'---2'                       => '',
			'--3'                        => 'Unique Product Identifiers',
			'brand'                      => 'Manufacturer[brand]',
			'upc'                        => 'GTIN[gtin]',
			'sku'                        => 'MPN[mpn]',
			'identifier_exists'          => 'Identifier Exist[identifier_exists]',
			'---3'                       => '',
			'--4'                        => 'Detailed Product Attributes',
			'item_group_id'              => 'Item Group Id[item_group_id]',
			'color'                      => 'Color[color]',
			'gender'                     => 'Gender[gender]',
			'age_group'                  => 'Age Group[age_group]',
			'material'                   => 'Material[material]',
			'pattern'                    => 'Pattern[pattern]',
			'size'                       => 'Size of the item[size]',
			'size_type'                  => 'Size Type[size_type]',
			'size_system'                => 'Size System[size_system]',
			'---4'                       => '',
			'--5'                        => 'Tax & Shipping',
			'tax'                        => 'Tax[tax]',
			'tax_country'                => 'Tax Country[tax_country]',
			'tax_region'                 => 'Tax Region[tax_region]',
			'tax_rate'                   => 'Tax Rate[tax_rate]',
			'tax_ship'                   => 'Tax Ship[tax_ship]',
			'tax_category'               => 'Tax[tax_category]',
			'shipping_country'           => 'Shipping Country',
			'shipping_region'            => 'Shipping Region',
			'shipping_service'           => 'Shipping Service',
			'shipping_price'             => 'Shipping Price',
			'weight'                     => 'Shipping Weight[shipping_weight]',
			'length'                     => 'Shipping Length[shipping_length]',
			'width'                      => 'Shipping Width[shipping_width]',
			'height'                     => 'Shipping Height[shipping_height]',
			'shipping_label'             => 'Shipping Label[shipping_label]',
			'---5'                       => '',
			'--6'                        => 'Product Combinations',
			'multipack'                  => 'Multipack[multipack]',
			'is_bundle'                  => 'Is Bundle[is_bundle]',
			'---6'                       => '',
			'--7'                        => 'Adult Products',
			'adult'                      => 'Adult[adult]',
			'---7'                       => '',
			'--8'                        => 'AdWord Attributes',
			'adwords_redirect'           => 'Adwords Redirect[adwords_redirect]',
			'---8'                       => '',
			'--9'                        => 'Custom Label Attributes',
			'custom_label_0'             => 'Custom label 0 [custom_label_0]',
			'custom_label_1'             => 'Custom label 1 [custom_label_1]',
			'custom_label_2'             => 'Custom label 2 [custom_label_2]',
			'custom_label_3'             => 'Custom label 3 [custom_label_3]',
			'custom_label_4'             => 'Custom label 4 [custom_label_4]',
			'---9'                       => '',
			'--10'                       => 'Additional Attributes',
			'excluded_destination'       => 'Excluded Destination[excluded_destination]',
			'included_destination'       => 'Included Destination[included_destination]',
			'expiration_date'            => 'Expiration Date [expiration_date]',
			'---10'                      => '',
			'--11'                       => 'Unit Prices (EU Countries and Switzerland Only)',
			'unit_pricing_measure'       => 'Unit Pricing Measure[unit_pricing_measure]',
			'unit_pricing_base_measure'  => 'Unit Pricing Base Measure[unit_pricing_base_measure]',
			'installment_months'         => 'Installment Months[months]',
			'installment_amount'         => 'Installment Amount[amount]',
			'subscription_period'        => 'Subscription Period[period]',
			'subscription_period_length' => 'Subscription Period Length[period_length]',
			'subscription_amount'        => 'Subscription Amount[amount]',
			'---11'                      => '',
			'--12'                       => 'Energy Labels',
			'energy_efficiency_class'    => 'Energy Efficiency Class[energy_efficiency_class]',
			'---12'                      => '',
			'--13'                       => 'Loyalty Points (Japan Only)',
			'loyalty_points'             => 'loyalty_points[loyalty_points]',
			'---13'                      => '',
			'--14'                       => 'Multiple Installments (Brazil Only)',
			'installment'                => 'Installment[installment]',
			'---14'                      => '',
			'--15'                       => 'Merchant Promotions Attribute',
			'promotion_id'               => 'Promotion Id[promotion_id]',
			'---15'                      => '',
		];

		return $attributes;
	}
}
